api_version: v1
kind: workflow
name: alpine-sysinfo

sandbox:
  mode: auto
  memory_mb: 256
  vcpus: 1
  image: "alpine:3.20"

workflow:
  steps:
    - name: sysinfo
      run:
        program: cat
        args: ["/etc/os-release"]

    - name: upcase
      depends_on: [sysinfo]
      run:
        program: tr
        args: ["a-z", "A-Z"]
        stdin_from: sysinfo

  output_step: upcase
